### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by krober10nd** [samuelburbulla/dune-mmesh#10]
* For publication in JOSS, a section needs to added informing new users how they can contribute to this package.

**Comment by samuelburbulla** [comment]
There is a section "Contribution" in the README referring to the GitLab/GitHub instance.

 Is there something missing that has to be included here?

**Comment by krober10nd** [comment]
Okay didn't see that but could be nice to say more explicitly the steps to contribute. Start a fork, do your changes, open a pull request, etc. up to you.
