### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by krober10nd** [samuelburbulla/dune-mmesh#4]
Following up on #2, how can an installation of dune-mesh be tested on a new system? And when new functionality is added?

**Comment by samuelburbulla** [comment]
We provide a test script in `dune-mmesh/scripts/test.py` that runs through all essential python functionality.

This `test.py` script is tested in our CI, so any new functionality should go into this script at the moment.
Do you think we have to split this into several unit tests already?

**Comment by samuelburbulla** [comment]
Of course, the C++ backend is tested separately in `dune/mmesh/test/`.

**Comment by samuelburbulla** [comment]
I implemented an easier test functionality to test your installation on a new system.

Now, on master, you can run
```
python -m dune.mmesh test
````
to run the python tests of dune-mmesh.

I'm looking forward to put this also in the next package on PyPI.
This will take some time however as it requires the next update of the DUNE Core modules.
