### ISSUE TITLE
Computational cost associated with mesh adapatation 

### ISSUE THREAD

**Issue by krober10nd** [samuelburbulla/dune-mmesh#6]
* It would be helpful to know what is the additional computational cost associated with mesh adaptation for a moving interface problem for example in 2D.

**Comment by samuelburbulla** [comment]
Yes, definitely a question which is interesting to investigate.
What is a reasonable test case to compare with?
Do you have a specific problem/method in mind which we should use as reference?

**Comment by krober10nd** [comment]
Perhaps everybody's favorite Burgers equation? It would also be good to throw into the mix explicit time stepping because if the mesh quality is compromised, the whole solver stops.

**Comment by samuelburbulla** [comment]
For the purpose of runtime comparison, I extended the moving example by a cell where we only evaluate the FV scheme without adaptation. In this example, we just solve the transport equation, but I think this is sufficient.
I attached a screenshot below how it looks like as this is not yet visible on the RTD page.
This comparison also nicely shows the advantage of moving the interface to keep the front sharp.

![Screenshot](https://user-images.githubusercontent.com/34940349/166637233-d8cbf4f9-8acc-4579-ac65-5e7a43619704.png)

it is a fair question whether we should not look at explicit time stepping. I will implement some adaptive time stepping for the same example such that we can see the influences of the mesh quality.

**Comment by samuelburbulla** [comment]
Now, time stepping in the example is explicit. The minimal time step size in the scheme with the adapted mesh is 0.0065, in contrast to 0.0354 for the standard version, due to mesh quality. Of course, this increases the overall runtime of the adapted scheme. Remarkably, the solution of standard scheme is significantly less diffuse now.

![Screenshot](https://user-images.githubusercontent.com/34940349/166644492-838dd04f-d64c-47c5-8003-240c75dae7a0.png)

**Comment by krober10nd** [comment]
So with the explicit (implicit) and without mesh adaptation is 10x (7x) than with mesh adaptation? Would it be possible to normalize this based on the global solution error? 

Then we could try reducing the mesh adaptation frequency. I assume it's adapting every timestep but likely this is not necessary.

**Comment by krober10nd** [comment]
I think this is a very useful experiment by the way, thanks for showing it. In my experience, cost-benefit analysis is the first thing that comes up during any kind of presentation w.r.t. to mesh adaptation.

**Comment by samuelburbulla** [comment]
Yes, it's about 10x, but the runtime factor decreases a little when I refine the mesh (below its 4x with half mesh size).

I am not really sure how you would normalise the error with respect to runtime? When we compare the L2-errors of both solutions we get an improvement of about 5x, but this might change under mesh refinement. 

Important is also to note that there might be a structural advantage depending on the exact solution you choose. For instance, a piecewise constant solution with a discontinuity only at the interface would have zero error in the adapted version. This is also one argument for not only looking at runtime here, you might get a structural benefit you might prefer.

The mesh adaptation frequency can be reduced by checking if cells have marked, and I added this check, but it seems that the mesh needs/wants to be adapted in most of the steps.

Standard explicit FV:
<img width="881" alt="standard" src="https://user-images.githubusercontent.com/34940349/168096612-37bcecfd-4f59-4d8d-b1f8-bc7154bc8787.png">

With adaptation:
<img width="886" alt="adapted" src="https://user-images.githubusercontent.com/34940349/168096604-9084e3fc-4adb-4236-9d66-252a9351be1e.png">

**Comment by krober10nd** [comment]
Okay, I appreciate the complexity in the analysis. I think the notebooks are helpful for user applications.
