### ISSUE TITLE
Interpolation between meshes 

### ISSUE THREAD

**Issue by krober10nd** [samuelburbulla/dune-mmesh#7]
* How are the solutions interpolated between consecutive meshes? Is there any special care taken in this step?

**Comment by samuelburbulla** [comment]
There is no interpolation between two consecutive meshes.
We take care about this with a moving mesh method taking into account the vertex movement, see [moving](https://dune-mmesh.readthedocs.io/en/latest/examples/moving.html) example.

Of course, after moving, we adapt the mesh to ensure mesh quality, but this is without movement.

**Comment by krober10nd** [comment]
I see, this wasn't immediately clear to me. Perhaps it could be emphasized that that this is a moving mesh type adaptation.

**Comment by krober10nd** [comment]
moving interface does not necessarily equate to moving meshes for me at least.

**Comment by samuelburbulla** [comment]
I agree that it does not necessarily equate.
In the paper, I will try to emphasize that we consider moving mesh type adaptation.
